### ISSUE TITLE
Cannot be built using Xcode 15.0.0

### ISSUE THREAD

**Issue by kristofkalai** [syt2/AssociatedObjectMacro#1]
On Xcode 14.3.1 the library cannot be added to any project, since:
`package 'associatedobjectmacro' @ 1.0.1 is using Swift tools version 5.9.0 but the installed version is 5.8.0`

Which is understandable, but Xcode 15.0.0 says (among some warnings):
- `'_' can only appear in a pattern or on the left side of an assignment` on line 142 in the file `AssociatedObjectMacro.swift`,
- `Cannot call value of non-function type 'AccessorBlockSyntax.Accessors'` and `Instance member 'accessors' cannot be used on type 'AccessorBlockSyntax'` on line 118 in the file `AssociatedObjectMacro.swift`.

Can you fix these please? 🙏  Or what have I done wrong?

(I think the solution could be that instead of 

`switch accessor {`

on line 117 in the file `AssociatedObjectMacro.swift` you should write 

`switch accessor.accessors {`.)

**Comment by syt2** [comment]
Thank you for your reminder. 
I have fixed this issue in the latest version.
